const Lists=[
    {
      "id": 1,
      "name": "ABC Corporation",
      "address": "123 Main St",
      "zip": "12345",
      "country": "USA",
      "employeeCount": 100,
      "industry": "Technology",
      "marketCap": 1000000000,
      "domain": "abccorp.com",
      "logo": "https://example.com/logo1.png",
      "ceoName": "John Smith"
    },
    {
      "id": 2,
      "name": "XYZ Corp",
      "address": "456 Park Ave",
      "zip": "67890",
      "country": "Canada",
      "employeeCount": 500,
      "industry": "Finance",
      "marketCap": 500000000,
      "domain": "xyzcorp.ca",
      "logo": "https://example.com/logo2.png",
      "ceoName": "Jane Doe"
    },
    {
      "id": 3,
      "name": "Acme Inc.",
      "address": "789 Broadway",
      "zip": "54321",
      "country": "UK",
      "employeeCount": 50,
      "industry": "Retail",
      "marketCap": 25000000,
      "domain": "acmeinc.co.uk",
      "logo": "https://example.com/logo3.png",
      "ceoName": "Michael Johnson"
    },
    {
      "id": 4,
      "name": "Tech Solutions Ltd.",
      "address": "101 Tech Blvd",
      "zip": "13579",
      "country": "Australia",
      "employeeCount": 200,
      "industry": "Technology",
      "marketCap": 800000000,
      "domain": "techsolutions.com.au",
      "logo": "https://example.com/logo4.png",
      "ceoName": "Emily Brown"
    },
    {
      "id": 5,
      "name": "Global Manufacturing",
      "address": "222 Industrial Rd",
      "zip": "56789",
      "country": "USA",
      "employeeCount": 1000,
      "industry": "Manufacturing",
      "marketCap": 1500000000,
      "domain": "globalmfg.com",
      "logo": "https://example.com/logo5.png",
      "ceoName": "Robert White"
    },
    {
      "id": 6,
      "name": "Food Delights",
      "address": "333 Culinary Ave",
      "zip": "24680",
      "country": "Canada",
      "employeeCount": 80,
      "industry": "Food",
      "marketCap": 30000000,
      "domain": "fooddelights.ca",
      "logo": "https://example.com/logo6.png",
      "ceoName": "Sarah Lee"
    },
    {
      "id": 7,
      "name": "Financial Strategies",
      "address": "444 Wealth St",
      "zip": "97531",
      "country": "UK",
      "employeeCount": 150,
      "industry": "Finance",
      "marketCap": 700000000,
      "domain": "financialstrategies.co.uk",
      "logo": "https://example.com/logo7.png",
      "ceoName": "James Anderson"
    },
    {
      "id": 8,
      "name": "EcoTech Solutions",
      "address": "555 Green Rd",
      "zip": "54321",
      "country": "Australia",
      "employeeCount": 300,
      "industry": "Environment",
      "marketCap": 600000000,
      "domain": "ecotechsolutions.com.au",
      "logo": "https://example.com/logo8.png",
      "ceoName": "Sophia Davis"
    },
    {
      "id": 9,
      "name": "Fashion Trends Inc.",
      "address": "666 Style Ave",
      "zip": "13579",
      "country": "USA",
      "employeeCount": 75,
      "industry": "Fashion",
      "marketCap": 35000000,
      "domain": "fashiontrends.com",
      "logo": "https://example.com/logo9.png",
      "ceoName": "William Johnson"
    },
    {
      "id": 10,
      "name": "Healthcare Solutions",
      "address": "777 Wellness Rd",
      "zip": "24680",
      "country": "Canada",
      "employeeCount": 400,
      "industry": "Healthcare",
      "marketCap": 900000000,
      "domain": "healthcaresolutions.ca",
      "logo": "https://example.com/logo10.png",
      "ceoName": "Olivia Martin"
    }
  ]
  export default Lists;